mainApp:
  replicaCount: 1
  namespace: <+infra.namespace>
  test: chart-examplelocal----chart-<+infra.namespace>-examplelocal
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent

subchartService:
  replicaCount: 1
  namespace: <+infra.namespace>
  test: 'chart-<+secrets.getValue("account.test")>-example.local----chart-<+infra.namespace>-example.local'
  image:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent
