apiVersion: apps/v1
kind: Deployment
metadata:
  name: subchart-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: subchart-service
  template:
    metadata:
      labels:
        app: subchart-service
        app2: {{ .Values.test }}
    spec:
      containers:
        - name: subchart-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
